[workspace]
resolver = "3"
members = [
    "crates/descar-core",
    "crates/descar-cli",
    "crates/descar",
]

[workspace.dependencies]
insta = { version = "1.48.0", features = ["yaml", "redactions", "filters"] }
thiserror = "2.0.20"
ariadne = { version = "0.6.0", features = ["auto-color"] }

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
# Performance
inefficient_to_string = "warn"
