[package]
name = "descar-core"
version = "0.1.0"
edition = "2024"
authors = ["Giuseppe Bianconi (Giuseppe-Bianc) <bianconig6@gmail.com>"]
repository = "https://github.com/Giuseppe-Bianc/Descar"
license = "Apache-2.0"
readme = "../../README.md"
keywords = ["rust", "compiler", "lexer"]
categories = ["compilers"]

[lints]
workspace = true

[dependencies]
insta = { workspace = true }
thiserror = { workspace = true }
console = { workspace = true }
regex = { workspace = true }