use std::fmt;

use super::token_kind::TokenKind;

impl fmt::Display for TokenKind {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AndEqual => f.write_str("'&='"),
            Self::OrEqual => f.write_str("'|='"),
            Self::ShiftLeftEqual => f.write_str("'<<='"),
            Self::ShiftRightEqual => f.write_str("'>>='"),
            Self::StarEqual => f.write_str("'*='"),
            Self::SlashEqual => f.write_str("'/='"),
            Self::PlusEqual => f.write_str("'+='"),
            Self::MinusEqual => f.write_str("'-='"),
            Self::EqualEqual => f.write_str("'=='"),
            Self::NotEqual => f.write_str("'!='"),
            Self::LessEqual => f.write_str("'<='"),
            Self::GreaterEqual => f.write_str("'>='"),
            Self::PlusPlus => f.write_str("'++'"),
            Self::MinusMinus => f.write_str("'--'"),
            Self::OrOr => f.write_str("'||'"),
            Self::AndAnd => f.write_str("'&&'"),
            Self::ShiftLeft => f.write_str("'<<'"),
            Self::ShiftRight => f.write_str("'>>'"),
            Self::PercentEqual => f.write_str("'%='"),
            Self::XorEqual => f.write_str("'^='"),
            Self::BitwiseNot => f.write_str("'~'"),
            Self::Plus => f.write_str("'+'"),
            Self::Minus => f.write_str("'-'"),
            Self::Star => f.write_str("'*'"),
            Self::Slash => f.write_str("'/'"),
            Self::Less => f.write_str("'<'"),
            Self::Greater => f.write_str("'>'"),
            Self::Not => f.write_str("'!'"),
            Self::Xor => f.write_str("'^'"),
            Self::Percent => f.write_str("'%'"),
            Self::Or => f.write_str("'|'"),
            Self::And => f.write_str("'&'"),
            Self::Equal => f.write_str("'='"),
            Self::Colon => f.write_str("':'"),
            Self::Comma => f.write_str("','"),
            Self::Dot => f.write_str("'.'"),
            Self::KeywordFun => f.write_str("'fun'"),
            Self::KeywordIf => f.write_str("'if'"),
            Self::KeywordElse => f.write_str("'else'"),
            Self::KeywordReturn => f.write_str("'return'"),
            Self::KeywordWhile => f.write_str("'while'"),
            Self::KeywordFor => f.write_str("'for'"),
            Self::KeywordMain => f.write_str("'main'"),
            Self::KeywordVar => f.write_str("'var'"),
            Self::KeywordConst => f.write_str("'const'"),
            Self::KeywordNullptr => f.write_str("'nullptr'"),
            Self::KeywordBreak => f.write_str("'break'"),
            Self::KeywordContinue => f.write_str("'continue'"),
            Self::KeywordBool(value) => write!(f, "boolean '{value}'"),
            Self::IdentifierAscii(value) | Self::IdentifierUnicode(value) => write!(f, "identifier '{value}'"),
            Self::Numeric(value) => write!(f, "number '{value}'"),
            Self::Binary(value) => write!(f, "binary '{value}'"),
            Self::Octal(value) => write!(f, "octal '{value}'"),
            Self::Hexadecimal(value) => write!(f, "hexadecimal '{value}'"),
            Self::InvalidBaseNumber => f.write_str("invalid base number"),
            Self::StringLiteral(value) => write!(f, "string literal \"{value}\""),
            Self::UnterminatedString => f.write_str("unterminated string literal"),
            Self::CharLiteral(value) => write!(f, "character literal '{value}'"),
            Self::UnterminatedChar => f.write_str("unterminated character literal"),
            Self::OpenParen => f.write_str("'('"),
            Self::CloseParen => f.write_str("')'"),
            Self::OpenBracket => f.write_str("'['"),
            Self::CloseBracket => f.write_str("']'"),
            Self::OpenBrace => f.write_str("'{'"),
            Self::CloseBrace => f.write_str("'}'"),
            Self::Semicolon => f.write_str("';'"),
            Self::TypeI8 => f.write_str("'i8'"),
            Self::TypeI16 => f.write_str("'i16'"),
            Self::TypeI32 => f.write_str("'i32'"),
            Self::TypeI64 => f.write_str("'i64'"),
            Self::TypeU8 => f.write_str("'u8'"),
            Self::TypeU16 => f.write_str("'u16'"),
            Self::TypeU32 => f.write_str("'u32'"),
            Self::TypeU64 => f.write_str("'u64'"),
            Self::TypeF32 => f.write_str("'f32'"),
            Self::TypeF64 => f.write_str("'f64'"),
            Self::TypeChar => f.write_str("'char'"),
            Self::TypeString => f.write_str("'string'"),
            Self::TypeBool => f.write_str("'bool'"),
            Self::Whitespace => f.write_str("whitespace"),
            Self::Comment => f.write_str("comment"),
            Self::MultilineComment => f.write_str("multiline comment"),
            Self::UnterminatedComment => f.write_str("unterminated multiline comment"),
            Self::Eof => f.write_str("end of file"),
        }
    }
}
