name: Rust CI

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  INSTA_UPDATE: no

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        rust: [ stable, beta, nightly ]
        include:
          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
          - os: macOS-latest
            rust: stable
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
          components: rustfmt, clippy
          override: true

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.rust }}-
            ${{ runner.os }}-cargo-

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --verbose

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --verbose

      - name: Clippy Lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --verbose -- -D warnings
